services:
  db:
    image: postgres:18
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: example
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
    volumes:
      - db:/var/lib/postgresql/18/docker
  migrations:
    image: migrate/migrate:4
    depends_on:
      db:
        condition: service_healthy
    command:
      - "-path=/migrations"
      - "-database=postgres://postgres:example@db:5432/postgres?sslmode=disable"
      - "up"
    volumes:
      - ./src/migrations:/migrations
volumes:
  db:
