[[language]]
name = "sql"
language-servers = ["sqls"]
auto-format = true
formatter = { command = "sqlfluff", args = [
  "format",
  "--dialect",
  "postgres",
  "-",
] }

[language-server.sqls]
command = "sqls"

[language-server.yaml-language-server.config.yaml.schemas]
"https://json.schemastore.org/github-workflow.json" = ".github/workflows/*.yaml"
