name: Deployment
on:
  push:
    tags:
      - "v*.*.*"
jobs:
  deploy:
    uses: hcubasd/fuzzy-garbanzo/.github/workflows/fuzzy-garbanzo.yaml@v0.1.3
    with:
      registry: ghcr.io
      repository: curly-spoon
    secrets:
      username: ${{github.actor}}
      password: ${{secrets.GITHUB_TOKEN}}
    permissions:
      contents: write
      packages: write
